version = 1

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"